### ISSUE TITLE
Top right X on "Incoming VID" screen not working

### ISSUE THREAD

**Issue by celinenilla** [idpass/idpass-mosip-resident-app#159]
CURRENT BEHAVIOUR
When clicking X in top right corner on the "Incoming VID" screen nothing happens

EXPECTED BEHAVIOUR
X should either not be displayed or it should have an effect, supposedly equivalent to "Reject"

**Comment by kneckinator** [comment]
Please close this issue @celinenilla if it was included in 0.2.0

**Comment by celinenilla** [comment]
Verified on 0.2.0 (0457). Working as expected, clicking "X" on "Incoming VID" screen will trigger a message on both devices that sharing has been rejected.
