### ISSUE TITLE
Improvements for the location permission which prompts during first time setup

### ISSUE THREAD

**Issue by elahonoridez** [idpass/idpass-mosip-resident-app#66]
Currently, the app prompts user during first time setup for location permissions. We will have to decide if we need to improve this or keep the behaviour as is.

<img src="https://user-images.githubusercontent.com/75471103/145944051-442de459-1664-4424-a518-f51c2baf841d.jpg" width="300" height="700">

**ISSUE:** The location permission is a sensitive one, we should not ask for it without any good reason and it should display some text to explain the reason before permission acquisition dialog. In this case it is required for Nearby share API to use bluetooth for data sharing.

**Reason behind this:** It is mostly needed for Nearby Connections. Right now, it is displayed at first launch because the permissions are called on android https://github.com/idpass/idpass-mosip-resident-app/blob/develop/frontend/android/app/src/main/java/io/mosip/residentapp/MainActivity.java#L62

**Options for changing:** 
As per @rjmangubat23  : `If we don't want it at first launch. I think we will have to implement it via react native way like something like this -> https://reactnative.dev/docs/permissionsandroid`

As per @uocnb : `We will need to delegate the permission acquisition for RA app, so we can control when it should ask for this.`

**Comment by kneckinator** [comment]
I will close this issue and later discussions and issues handles this.
